[WIP] Nrt tezos get current delegate
LedgerHQ/lib-ledger-core pull request #674
Opened 2020-11-30 16:32 UTC by twilgenbus-ledger

This PR adds a new function to an XTZ account: `getCurrentDelegate`
It allows the caller to retrieve the address of the current delegation, empty if none.

2020-11-30 16:49 UTC, hlafet-ledger requested changes

2020-11-30 16:49 UTC, hlafet-ledger commented on core/src/wallet/tezos/TezosLikeAccount.h
> +            FuturePtr<std::string> getCurrentDelegate();
The function cannot be called by users of the libcore if not defined in the interface.

2020-11-30 16:49 UTC, hlafet-ledger commented on core/src/wallet/tezos/TezosLikeAccount2.cpp
> +                return std::make_shared<std::string>(*delegate);
Is it necessary to create a new string object ?

2020-11-30 16:49 UTC, hlafet-ledger commented on core/src/wallet/tezos/explorers/TezosLikeBlockchainExplorer.cpp
> +                        return "";
How to make difference between network issue for example and adresses without delegate ?

2020-12-01 15:28 UTC, twilgenbus-ledger commented
Merged to allow usage of CI

2020-12-01 15:28 UTC, merged