Read-only DB session pool created
LedgerHQ/lib-ledger-core pull request #710
Opened 2021-01-22 09:15 UTC by hzheng-ledger

2021-01-26 08:46 UTC, pollastri-pierre requested changes
Can you make the ReadOnly connection pool configurable through the DatabaseBackend class? it will allow us to fine tune the daemon depending on the needs and machines.

2021-01-28 09:01 UTC, pollastri-pierre requested changes
It's just missing a change on this djinni method
 static getPostgreSQLBackend(connectionPoolSize: i32): DatabaseBackend;
To be able to set the read only connection pool.

2021-01-29 07:38 UTC, hzheng-ledger commented
> It's just missing a change on this djinni method
> static getPostgreSQLBackend(connectionPoolSize: i32): DatabaseBackend;
> To be able to set the read only connection pool.

Fixed

2021-01-29 09:46 UTC, pollastri-pierre approved these changes

2021-01-29 09:53 UTC, pollastri-pierre approved these changes

2021-02-10 15:07 UTC, merged