Remove SQLite completely from the repository
LedgerHQ/lib-ledger-core pull request #887
Opened 2022-07-19 11:56 UTC by viktorb-ledger

This PR removes:
- core/lib/soci_sqlite3
- core/lib/sqlcipher
- core/test/database/MemoryDatabaseProxy.{cpp,h} - not used in the code
- core/test/database/database_soci_proxy_tests.cpp
- CI builds for Android and iOS

Side effects:
- CI is slower with PostgreSQL

2022-07-21 12:52 UTC, jcoatelen-ledger requested changes
the most significant change is to simply remove `PG_SUPPORT`

2022-07-21 13:08 UTC, BertrandD commented on core/src/api/DatabaseBackendType.cpp
> +    if (databaseBackendType == "POSTGRESQL") return DatabaseBackendType::POSTGRESQL;
This is a generated file :)

2022-07-21 13:35 UTC, viktorb-ledger commented on core/src/api/DatabaseBackendType.cpp
> +    if (databaseBackendType == "POSTGRESQL") return DatabaseBackendType::POSTGRESQL;
Yes. I doubt I can change this.

2022-07-21 14:35 UTC, viktorb-ledger commented on core/test/integration/BaseFixture.cpp
>                                                          bool usePostgreSQL,
We can't remove this because there are tests that use a custom `httpClient`.

2022-07-21 14:38 UTC, BertrandD commented on core/test/integration/BaseFixture.cpp
>                                                          bool usePostgreSQL,
Sorry, misclicked the wrong line, I was talking about the usePostgreSQL parameter

2022-07-21 14:43 UTC, viktorb-ledger commented on core/test/coin-integration/common/CoinIntegrationFixture.hpp
> +        configuration->putString(api::PoolConfiguration::DATABASE_NAME, "postgres://localhost:5432/test_db");
Do you think `core/idl/wallet/configuration.djinni` is a proper place?

2022-07-21 14:51 UTC, viktorb-ledger commented on core/test/integration/BaseFixture.cpp
>                                                          bool usePostgreSQL,
done :)

2022-07-21 14:51 UTC, viktorb-ledger commented on core/test/integration/synchronization/synchronization_tests.cpp
> +
done

2022-07-25 08:25 UTC, viktorb-ledger commented on .github/workflows/clang-tidty-review.yml
> +          apt_packages: libssl-dev,libpq-dev,libpqxx-dev,postgresql-server-dev-all
`libpq-dev` and `postgresql-server-dev-all` are required

2022-07-25 08:27 UTC, merged